name: Build APK

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.2.4

      - name: Set up JDK 17
        uses: actions/setup-java@v2.2.4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Run tests
        run: ./gradlew test

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
